name: Build EXE for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build EXE
      run: pyinstaller --onefile hrtr1_fixed.py

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: hrtr1_exe
        path: dist/hrtr1_fixed.exe
