name: Build EXE for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile hrtr1_fixed.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: hrtr1_fixed_exe
          path: dist/hrtr1_fixed.exe
