name: Build EXE for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask pyinstaller

      - name: Clean previous builds
        run: |
          if exist build rmdir /s /q build
          if exist dist rmdir /s /q dist

      - name: Build EXE
        run: pyinstaller --onefile hrtr1_fixed.py

      - name: Check EXE exists
        run: |
          if not exist dist\hrtr1_fixed.exe (
            echo "❌ الملف لم يتم إنشاؤه"
            exit 1
          )

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: hrtr1_fixed_exe
          path: dist/hrtr1_fixed.exe
